# Generated by Django 4.2 on 2025-02-14 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GmailUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gmail', models.TextField(unique=True)),
                ('total_messages', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='GmailMessage',
            fields=[
                ('message_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('gmail_id', models.IntegerField()),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('sender', models.TextField()),
                ('received_at', models.DateTimeField()),
                ('prediction', models.CharField(choices=[('spam', 'Spam'), ('ham', 'Ham'), ('phishing', 'Phishing')], default='ham', max_length=20)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmail_messages.gmailuser')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-received_at'],
            },
        ),
    ]
