# Generated by Django 4.2 on 2025-02-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmailmessage',
            name='message_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
